### ISSUE TITLE
Some base colors not swapped between light and dark

### ISSUE THREAD

**Issue by jibsen** [SublimeColors/Solarized#16]
There are a number of places where the base colors are not swapped between the light and dark theme - for instance `entity.name.function.c`, which results in C function names having the same color as comments when using the dark theme.

It might be helpful to fix one theme and then produce the other automatically by substitution of the base colors, to avoid them "getting out of sync"?

**Comment by braver** [comment]
I've seen some other efforts that use a workable syntax like cson or yaml to build themes and yeah, that makes a lot of sense. However, I just went for some elbow grease and cleaned the themes out. Really for another couple years of use I think ;)
