### ISSUE TITLE
Build with TravisCI

### ISSUE THREAD

**Issue by Iristyle** [SublimeColors/Solarized#2]
It would be nice to run a script for pulls that would pass / fail based on whether or not the file was well formed... and that it contained only the accepted colors.

Shouldn't be too hard to put something together with Node to enforce that.

**Comment by braver** [comment]
The definitions are super reduced right now, and it kinda feels like more work to build tests for this than just plain paying attention. Should not be much work into it anymore as it's not so confusing anymore trying to match some half-assed vim screenshots.
