### ISSUE TITLE
Change selection background color to something more readable

### ISSUE THREAD

**Issue by kavika13** [SublimeColors/Solarized#28]
The Solarized website uses ~~magenta~~ "Hot Pink" (#FF5E99) as the selection background color.

The dev notes say base2/base02 are the "background highlights" color.

See the [usage development notes on the Solarized website](http://ethanschoonover.com/solarized#usage-development).

Nowhere am I reading on the Solarized site that they suggest inverting the color scheme for selection highlights. I also think this is very hard to read.

I don't have VIM to see what it does ;)

I've e-mailed the Solarized author directly for clarification, and will post his reply inline here if he responds.

**Comment by braver** [comment]
Themes have been updated with new selection backgrounds.
