### ISSUE TITLE
Special words not highlighted

### ISSUE THREAD

**Issue by maletor** [SublimeColors/Solarized#30]
There are special words in Ruby / Rails that I'd like to see highlighted.

How do I go about adding these words? Realistically, I think this is a syntax definition issue. 

Attached is a side by side comparison. 

![screenshot 2014-07-01 14 43 27](https://cloud.githubusercontent.com/assets/138785/3449631/146adeca-0169-11e4-879d-469208ba1df4.png)

Any ideas here?

**Comment by braver** [comment]
Let me know if anything works out and give me example files of a pull request. In the mean time, realistically, I'm not going to monitor this and there is nothing I can do right now.
