### ISSUE TITLE
Brackets / commas color in PHP file

### ISSUE THREAD

**Issue by wickedsp1d3r** [SublimeColors/Solarized#32]
Is this normal (see brackets and comma)?

![brackets_solarized](https://cloud.githubusercontent.com/assets/1852854/3536526/e0eaa6c4-0812-11e4-82aa-ab3b79da7709.png)

If so, how could I change the color to normal (e.g. function name)?

**Comment by braver** [comment]
Punctuation has been redone, now better and consistent across languages.
