### ISSUE TITLE
variable.parameter block is blank, causes parameters to be assigned wrong colors (ST2)

### ISSUE THREAD

**Issue by geoelectric** [SublimeColors/Solarized#33]
The scope of the wrong-colored text is source.python meta.function.python meta.function.parameters.python variable.parameter.function.python. They're coming up #D33682.

They should be base0 (#839496) or base00 (#657b83)

I think the offending line is this:

https://github.com/SublimeColors/Solarized/blob/master/Solarized%20%28dark%29.tmTheme#L503

    <dict>
    <key>name</key>
    <string>SCSS: Variables (pink)</string>
    <key>scope</key>
    <string>variable, variable.scss</string>
    <key>settings</key>
    <dict>
    <key>foreground</key>
    <string>#D33682</string>
    </dict>
</dict>

I assume defining scope "variable" is a typo. However, there is a block for variable.parameter before this that should set to base and win the selection rules.

Deleting "variable," clears up the issue, though I can't speak to additional side effects.

**Comment by braver** [comment]
I did a bunch of cleaning up and as far as I can tell right now parameters seem to be in good shape.
