### ISSUE TITLE
Incorrect select colour in Sublime Text 3

### ISSUE THREAD

**Issue by johngb** [SublimeColors/Solarized#35]
If following the Solarized design, when selecting text the select colour should switch to the background colour of the alternate theme.  So if you're using the dark theme, your selection colour should be the background of the light theme and vice versa.  Additionally the text that is being selected should not change colour.

In the theme as it stands now, the select colour is incorrect, and the selected text changes colour to a single colour.

I'm not sure how to correct this, otherwise I'd just send a pull request.

**Comment by braver** [comment]
@johngb @jibsen @johngb Just as a heads-up kinda related to this topic. I finally got around to a full spring cleaning and rewrite of the theme. Basically already dumped about 50% of the lines of code, getting rid of a lot of legacy mess and instead going for internal consistency, maintainability and simplicity over the "original" vim screenshots. I'm also re-doing the selection background.

![screen shot 2015-02-09 at 19 45 59](https://cloud.githubusercontent.com/assets/2543659/6113086/e8c42156-b094-11e4-9c8e-815ea63d321a.png)

**Comment by braver** [comment]
Wasn't happy with a lot of stuff in the themes, and super unhappy with the selection colors. I really don't want to lose syntax colors inside a selection and flipping the theme is just doesn't work well (and can't even be done properly). The new stuff is probably not canonical, but canonical be damned: it looks great IMNSHO.

**Comment by jibsen** [comment]
I think the theme needed a major overhaul. I tried to clean it up a while ago, and ended up starting from scratch instead with only [a handful of base rules](https://github.com/jibsen/solarized_minimal), because it was near impossible to guess which rules in the 50k file somehow affected other rules.

Looking forward to seeing what you end up with :+1:.

**Comment by johngb** [comment]
Sounds good.  I spent some time with modifying the dark theme, and I agree that there is a lot of unnecessary code.

A definite :+1: for the new selection, which is much cleaner without having to invert the background.

**Comment by braver** [comment]
Thanks guys! :sparkles:
