### ISSUE TITLE
Colors Mismatch Between Sublime Text and Vim Versions.

### ISSUE THREAD

**Issue by Doppp** [SublimeColors/Solarized#40]
This might be a little off topic but does anyone else's Solarized colors look like this in Sublime? Braces are not blue, for example.

![screen shot 2015-02-06 at 2 03 50 pm](https://cloud.githubusercontent.com/assets/627410/6075201/05e12c5e-ae09-11e4-8851-a99369fffd44.png)

According to the main [Solarized](http://ethanschoonover.com/solarized) site, it's supposed to look like (in Vim): 

![](http://ethanschoonover.com/solarized/img/screen-javascript-dark.png)

**Comment by braver** [comment]
This implementation of Solarized doesn't aim to match the screenshots of the original. Vim has its limitations and inconsistencies, and Sublime has its own. For instance, some syntax definitions don't allow you to define colors for braces. You have to work around that. Also, I think not having any differentiation inside a regex is not ideal, so why shouldn't we add that?
