### ISSUE TITLE
Support functions same color as comments

### ISSUE THREAD

**Issue by jibsen** [SublimeColors/Solarized#41]
I noticed that `support.function` (like `scanf` in the screenshot below) is the same color as comments, which I feel is perhaps a little confusing.

![solarized_red_z](https://cloud.githubusercontent.com/assets/1367512/6137855/98d1aebe-b17c-11e4-96b7-a13e990413d6.png)

Also, the red color on keywords appears to only color some operators (like `&` and `|`, but not `*` and `+`).

**Comment by braver** [comment]
I was able to just take out some definitions for grey text, mostly in php. Should solve that, but if it doesn't let me know (perhaps send an example file).

Keywords are red, except for `keyword.operator.comparison`, `keyword.operator.assignment`, `keyword.operator.arithmetic`. I kinda like it like that.

**Comment by jibsen** [comment]
The example file I used is test.c from the samples folder of the repository. As far as I can tell it is the rule for "C: Function" at line 623 that colors them base01. Removing the rule colors `scanf` red instead, but I don't know if this will affect other things.

Regarding operators, I feel it's a bit inconsistent that taking a variables address (`&foo`) is red, but dereferencing a pointer (`*bar`) is not. Unfortunately I don't think the grammar is good enough to differentiate these uses.

**Comment by braver** [comment]
Right, thanks. Might be a limitation of the c grammar, but I'll look into it.

**Comment by braver** [comment]
I was able to take out a lot of variation in the coloring of function names. They're now mostly `#b58900`. This also took out some errors in the way c syntax was colored. The grammar is a but limited, but your problem should be pretty much solved now.
![screen shot 2015-02-11 at 21 02 26](https://cloud.githubusercontent.com/assets/2543659/6155374/17f565c6-b233-11e4-9e1b-f501117e9569.png)
